apiVersion: v2
dependencies:
- name: reloader
  repository: https://stakater.github.io/stakater-charts
  version: 1.1.0
description: A Helm chart for Kubernetes
name: rdi
type: application
version: 1.4.0
