apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: rdi-operator
  labels:
    app: rdi-operator
    product: rdi
subjects:
  - kind: ServiceAccount
    name: rdi-operator
roleRef:
  kind: Role
  name: rdi-operator
  apiGroup: rbac.authorization.k8s.io
