{{- if and .Values.global.openShift .Values.route.tls.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: rdi-api-route-tls
  labels:
    app: rdi-api
    product: rdi
type: kubernetes.io/tls
data:
  tls.crt: {{ .Values.route.tls.crt | b64enc | quote }}
  tls.key: {{ .Values.route.tls.key | b64enc | quote }}
{{- end }}
