{{- if .Values.global.rdiSysSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: rdi-sys-config
  labels:
    product: rdi
type: Opaque
data:
  {{- range $sysSecretKey, $sysSecretValue := .Values.global.rdiSysSecret }}
    {{- if $sysSecretValue }}
    {{ $sysSecretKey }}: {{ $sysSecretValue | b64enc | quote }}
    {{- end }}
  {{- end }}
{{- end }}
