{{- if and .Values.ingress.enabled .Values.ingress.tls.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: rdi-api-ingress-tls
  labels:
    app: rdi-api
    product: rdi
type: kubernetes.io/tls
data:
  {{- range $tlsSecretKey, $tlsSecretValue := .Values.ingress.tls }}
    {{- if $tlsSecretValue }}
    {{ $tlsSecretKey }}: {{ $tlsSecretValue | b64enc | quote }}
    {{- end }}
  {{- end }}
{{- end }}
