apiVersion: v1
kind: Service
metadata:
  name: rdi-metrics-exporter
  labels:
    app: rdi-metrics-exporter
    product: rdi
spec:
  selector:
    app: rdi-metrics-exporter
  ports:
    - name: rdi-metrics
      protocol: {{ .Values.rdiMetricsExporter.service.protocol }}
      port: {{ .Values.rdiMetricsExporter.service.port }}
      targetPort: {{ .Values.rdiMetricsExporter.service.targetPort }}
  type: {{ .Values.rdiMetricsExporter.service.type }}
