{{- if .Values.global.rdiDbSSLSecret.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: rdi-db-ssl-secret
  labels:
    product: rdi
type: Opaque
data:
  {{- if and .Values.global.rdiDbSSLSecret.cert .Values.global.rdiDbSSLSecret.key  }}
  cert: {{ .Values.global.rdiDbSSLSecret.cert | b64enc | quote }}
  key: {{ .Values.global.rdiDbSSLSecret.key | b64enc | quote }}
  {{- end }}
  {{- if .Values.global.rdiDbSSLSecret.cacert }}
  cacert: {{ .Values.global.rdiDbSSLSecret.cacert | b64enc | quote }}
  {{- end }}
{{- end }}
