apiVersion: v1
kind: Service
metadata:
  name: rdi-api
  labels:
    app: rdi-api
    product: rdi
spec:
  selector:
    app: rdi-api
  ports:
    - protocol: TCP
      port: {{ .Values.apiServer.service.port }}
      targetPort: {{ .Values.apiServer.service.targetPort }}
      {{- if eq .Values.apiServer.service.type "NodePort" }}
      nodePort: {{ .Values.apiServer.service.nodePort | default 30080 }}
      {{- end }}
  type: {{ .Values.apiServer.service.type }}