apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: rdi-api
  labels:
    app: rdi-api
    product: rdi
rules:
  - apiGroups:
      - apps
    resources:
      - pods
      - deployments
    verbs:
      - list
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - list
