apiVersion: apps/v1
kind: Deployment
metadata:
  name: rdi-api
  labels:
    app: rdi-api
    product: rdi
spec:
  replicas: {{ .Values.apiServer.replicas }}
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: rdi-api
      product: rdi
  template:
    metadata:
      labels:
        app: rdi-api
        product: rdi
      annotations:
        configmap.reloader.stakater.com/reload: rdi-sys-config
        secret.reloader.stakater.com/reload: rdi-sys-config, rdi-db-ssl-secret, target-db, target-db-ssl-secret
    spec:
      serviceAccountName: rdi-api
      terminationGracePeriodSeconds: 60
      {{- with .Values.global.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: rdi-api
          {{- include "securityContext" . | nindent 10 }}
          image: "{{ .Values.global.image.registry }}/{{ .Values.global.image.repository }}/{{ .Values.apiServer.image.name }}:{{ or .Values.apiServer.image.tag .Values.global.image.tag }}"
          imagePullPolicy: {{ .Values.apiServer.image.pullPolicy }}
          livenessProbe:
            httpGet:
              path: /
              port:  {{ .Values.apiServer.service.targetPort }}
            periodSeconds: {{ .Values.apiServer.liveness.periodSeconds }}
            failureThreshold: {{ .Values.apiServer.liveness.failureThreshold }}
          readinessProbe:
            httpGet:
              path: /
              port:  {{ .Values.apiServer.service.targetPort }}
            periodSeconds: {{ .Values.apiServer.readiness.periodSeconds }}
            failureThreshold: {{ .Values.apiServer.readiness.failureThreshold }}
          startupProbe:
            httpGet:
              path: /
              port: {{ .Values.apiServer.service.targetPort }}
            periodSeconds: {{ .Values.apiServer.startup.periodSeconds }}
            failureThreshold: {{ .Values.apiServer.startup.failureThreshold }}
          volumeMounts:
            - name: rdi-db-certificates
              mountPath: /etc/certificates/rdi_db
              readOnly: true
          env:
            - name: HOST_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
            - name: RDI_API_SERVER_PORT
              value: "{{ .Values.apiServer.service.targetPort }}"
          envFrom:
            - configMapRef:
                name: rdi-sys-config
            - secretRef:
                name: rdi-sys-config
            - secretRef:
                name: target-db
                optional: true
      volumes:
        - name: rdi-db-certificates
          secret:
            secretName: rdi-db-ssl-secret
            optional: true
        - name: target-db-certificates
          secret:
            secretName: target-db-ssl-secret
            optional: true
